"""Helpers that turn analysis results into LaTeX the manuscript can \\input{}.

This is the heart of the "no number is typed by hand" rule (CLAUDE.md §8):
regressions and summary statistics come in as Python objects and go out as
booktabs tables and in-text \\newcommand macros. Everything is deliberately
explicit so a reader can see exactly how a number reaches the paper.
"""
from __future__ import annotations
import pathlib


# --------------------------------------------------------------------------- #
# formatting
# --------------------------------------------------------------------------- #
def num(x, d: int = 3) -> str:
    """Format a float with `d` decimals; blank for missing."""
    if x is None or (isinstance(x, float) and x != x):  # NaN check
        return ""
    return f"{x:.{d}f}"


def stars(p: float) -> str:
    """Significance stars: *** p<.01, ** p<.05, * p<.1."""
    if p is None or p != p:
        return ""
    return "***" if p < 0.01 else "**" if p < 0.05 else "*" if p < 0.10 else ""


# --------------------------------------------------------------------------- #
# in-text macros:  \newcommand{\betaAbs}{-0.002}
# --------------------------------------------------------------------------- #
def write_macros(path: str | pathlib.Path, macros: dict[str, str]) -> None:
    """Write a `\\newcommand` per item so prose can cite numbers by name."""
    lines = [
        "% Auto-generated by code/02_analyze.py — DO NOT EDIT BY HAND.",
        "% Each macro is a number the manuscript cites in prose (CLAUDE.md §8).",
    ]
    for name, value in macros.items():
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")
    pathlib.Path(path).write_text("\n".join(lines) + "\n")


# --------------------------------------------------------------------------- #
# regression table (booktabs), with custom bottom rows (N, R^2, lambda, ...)
# --------------------------------------------------------------------------- #
def regression_table(
    path: str | pathlib.Path,
    models: list,
    column_labels: list[str],
    coef_order: list[str],
    coef_names: dict[str, str],
    extra_rows: list[tuple[str, list[str]]],
    caption: str,
    label: str,
    notes: str = "",
    coef_decimals: int = 4,
) -> None:
    """Emit a LaTeX regression table.

    models:        list of fitted statsmodels results (one per column)
    column_labels: header for each column
    coef_order:    parameter keys to display, in order
    coef_names:    map parameter key -> printed row name
    extra_rows:    list of (row label, [cell per model]) appended below coefs
                   (e.g. implied lambda, half-life, N, R^2)
    coef_decimals: decimals for coefficients/SEs (betas are small, default 4)
    """
    ncol = len(models)
    colspec = "l" + "c" * ncol
    out = [
        "% Auto-generated by code/02_analyze.py — DO NOT EDIT BY HAND.",
        "\\begin{table}[htbp]",
        "\\centering",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        f"\\begin{{tabular}}{{{colspec}}}",
        "\\toprule",
        " & " + " & ".join(column_labels) + " \\\\",
        "\\midrule",
    ]
    for key in coef_order:
        cells, se_cells = [], []
        for m in models:
            if key in m.params.index:
                b = m.params[key]
                se = m.bse[key]
                p = m.pvalues[key]
                cells.append(f"{num(b, coef_decimals)}{stars(p)}")
                se_cells.append(f"({num(se, coef_decimals)})")
            else:
                cells.append("")
                se_cells.append("")
        out.append(f"{coef_names.get(key, key)} & " + " & ".join(cells) + " \\\\")
        out.append(" & " + " & ".join(se_cells) + " \\\\")
    out.append("\\midrule")
    for label_text, cells in extra_rows:
        out.append(f"{label_text} & " + " & ".join(cells) + " \\\\")
    out += ["\\bottomrule", "\\end{tabular}"]
    if notes:
        out.append(f"\\\\[2pt]\n\\footnotesize {notes}")
    out.append("\\end{table}")
    pathlib.Path(path).write_text("\n".join(out) + "\n")


# --------------------------------------------------------------------------- #
# generic descriptive table from a DataFrame (booktabs), no jinja2 dependency
# --------------------------------------------------------------------------- #
_ESCAPE = {"&": r"\&", "%": r"\%", "_": r"\_", "#": r"\#", "$": r"\$",
           "<": r"\textless{}", ">": r"\textgreater{}"}


def _esc(x) -> str:
    s = "" if x is None or (isinstance(x, float) and x != x) else str(x)
    return "".join(_ESCAPE.get(ch, ch) for ch in s)


def dataframe_table(
    path: str | pathlib.Path,
    df,
    caption: str,
    label: str,
    index: bool = False,
    notes: str = "",
) -> None:
    """Emit a DataFrame as a booktabs table inside a floating environment.

    Builds the tabular by hand (no pandas Styler / jinja2), so the mapping from
    data to LaTeX is fully explicit and dependency-light.
    """
    cols = ([df.index.name or ""] if index else []) + [str(c) for c in df.columns]
    colspec = "l" * len(cols)
    header = " & ".join(_esc(c) for c in cols) + r" \\"
    rows = []
    for idx, row in df.iterrows():
        cells = ([_esc(idx)] if index else []) + [_esc(v) for v in row]
        rows.append(" & ".join(cells) + r" \\")
    out = [
        "% Auto-generated by code/ — DO NOT EDIT BY HAND.",
        "\\begin{table}[htbp]",
        "\\centering",
        f"\\caption{{{caption}}}",
        f"\\label{{{label}}}",
        f"\\begin{{tabular}}{{{colspec}}}",
        "\\toprule",
        header,
        "\\midrule",
        *rows,
        "\\bottomrule",
        "\\end{tabular}",
    ]
    if notes:
        out.append(f"\\\\[2pt]\n\\footnotesize {notes}")
    out.append("\\end{table}")
    pathlib.Path(path).write_text("\n".join(out) + "\n")
